"""GraphWorX32 GDF Parser: Neutral CFBF and MFC CArchive recovery library."""

from __future__ import annotations

from graphworx32_gdf_parser.aliases import (
    decode_experimental_local_aliases,
    read_experimental_cstring,
    read_mfc_cstring,
)
from graphworx32_gdf_parser.api import inventory_file, parse_gdf, read_contents
from graphworx32_gdf_parser.cfbf import OleFileAdapter
from graphworx32_gdf_parser.cursor import ArchiveCursor
from graphworx32_gdf_parser.errors import ExitStatus, GdfParserError, InventoryFailure
from graphworx32_gdf_parser.evidence import (
    ArchiveDecoder,
    ArchiveGrammar,
    EvidenceRegistry,
    decode_archive,
    inspect_contents,
    load_evidence_record,
    parse_evidence_record,
    production_registry,
)
from graphworx32_gdf_parser.models import (
    DEFAULT_LIMITS,
    ApprovedLayout,
    ArchiveClass,
    ArchiveEvent,
    ArchiveEventKind,
    ArchiveObject,
    ArchiveResult,
    CfbfEntry,
    Diagnostic,
    EntryType,
    EvidenceBasis,
    EvidenceFixture,
    EvidenceRecord,
    GdfDocument,
    GlobalAliasEvidence,
    Inventory,
    InventoryResult,
    Limits,
    MetadataProperty,
    ObjectLocalEvidence,
    ObjectLocalSet,
    ParseLimits,
    ParseResult,
    RawDynamicObject,
    ScreenProfileResult,
    Span,
    TrustedSpan,
)
from graphworx32_gdf_parser.screen import (
    build_opoint_map,
    clean_expression,
    discover_layers,
    extract_screen_profile,
    select_target_layer,
)

__version__ = "0.1.0"

__all__ = [
    "DEFAULT_LIMITS",
    "ApprovedLayout",
    "ArchiveClass",
    "ArchiveCursor",
    "ArchiveDecoder",
    "ArchiveEvent",
    "ArchiveEventKind",
    "ArchiveGrammar",
    "ArchiveObject",
    "ArchiveResult",
    "CfbfEntry",
    "Diagnostic",
    "EntryType",
    "EvidenceBasis",
    "EvidenceFixture",
    "EvidenceRecord",
    "EvidenceRegistry",
    "ExitStatus",
    "GdfDocument",
    "GdfParserError",
    "GlobalAliasEvidence",
    "Inventory",
    "InventoryFailure",
    "InventoryResult",
    "Limits",
    "MetadataProperty",
    "ObjectLocalEvidence",
    "ObjectLocalSet",
    "OleFileAdapter",
    "ParseLimits",
    "ParseResult",
    "RawDynamicObject",
    "ScreenProfileResult",
    "Span",
    "TrustedSpan",
    "build_opoint_map",
    "clean_expression",
    "decode_archive",
    "decode_experimental_local_aliases",
    "discover_layers",
    "extract_screen_profile",
    "inspect_contents",
    "inventory_file",
    "load_evidence_record",
    "parse_evidence_record",
    "parse_gdf",
    "production_registry",
    "read_contents",
    "read_experimental_cstring",
    "read_mfc_cstring",
    "select_target_layer",
]
